### PR TITLE
Add Hetzner timeformat tests

### PR DESCRIPTION
**Pull request by jobstoit**
Added tests for the HdnsTime UnmashalJSON

### CODE REVIEW

**Comment by jobstoit** [comment]
Also fixed a listing issue and added some comments

**Comment by jobstoit** [comment]
@DrBu7cher after merging this we could also increase the tag to 0.1.1 so you can use that in ExternalDNS

**Comment by DrBu7cher** [comment]
Merry christmas! :)

I'm so sorry for not looking into it yesterday. I got the notifications on my work mail address.
I didn't mean to push to the branch without asking you, sorry for that too.
I think we should add the RFC3339, since it is the format stated in the documentation.

Are you okay with the changes I made? :)

And I would like a new tag, after we merge this. :)

**Comment by jobstoit** [comment]
Merry Christmas!
No worries, looks good. I'll merge this and create the tag 0.1.1

**Pull request merged**
